export const DEFAULT_IVR_SAMPLE_MODULES = [
    {
        "nextModuleId": 13,
        "id": -1,
        "guid": "d1c8e5b7-9a0c-4f1b-9c3a-8e7c0d2e6f1b",
        "customerId": 2,
        "serviceModuleTypeId": 34,
        "name": "start",
        "order": 1,
        "serviceGroupId": 0,
        "callLogVisible": false
    },
     {
        "closedModuleId": 17,
        "timeZone": "Europe/Oslo",
        "id": 13,
        "guid": "b30dc35a-e0c4-4786-a090-a05af101e9d8",
        "customerId": 2,
        "serviceModuleTypeId": 5,
        "name": "Tidsstyring",
        "order": 0,
        "serviceGroupId": 0,
        "callLogVisible": true,
        "exits1": 8710,
        "exits2": 18,
        "exits3": -1,
        "exits4": -1,
        "exits5": -1,
        "exits6": -1,
        "exits7": -1,
        "exits8": -1
    },
    {
        "answer": true,
        "background": true,
        "soundFile": "007",
        "interval": 3,
        "count": 3,
        "key0ModuleId": 8710,
        "key1ModuleId": 14,
        "key2ModuleId": 15,
        "key3ModuleId": 8711,
        "key4ModuleId": 8710,
        "key5ModuleId": 8710,
        "key6ModuleId": 8710,
        "key7ModuleId": 8710,
        "key8ModuleId": 8710,
        "key9ModuleId": 8710,
        "keyStarModuleId": 8710,
        "keyHashModuleId": 8710,
        "loopExhaustedModuleId": 15,
        "surveyModule": false,
        "id": 8710,
        "guid": "30d0b64a-31ad-4eff-b9d6-fac90be5a3e0",
        "customerId": 2,
        "serviceModuleTypeId": 30,
        "name": "My menu",
        "order": 15,
        "serviceGroupId": 0,
        "callLogVisible": false
    },
    {
        "nextModuleId": 408,
        "internalLookup": true,
        "yellowPagesLookup": false,
        "id": 3472,
        "guid": "5547e9b8-9896-47b4-abc1-dc8fa941e230",
        "customerId": 2,
        "serviceModuleTypeId": 39,
        "name": "contactLookup",
        "order": 14,
        "serviceGroupId": 0,
        "callLogVisible": false
    },
    {
        "cause": "normal",
        "id": 16,
        "guid": "53f6b586-0d58-4fc4-abc7-8b766af742c0",
        "customerId": 2,
        "serviceModuleTypeId": 1,
        "name": "Slutt",
        "order": 7,
        "serviceGroupId": 0,
        "callLogVisible": true
    },
    {
        "cause": "normal",
        "id": 19,
        "guid": "e254c7ae-1cde-4f3c-a61d-87f046bf4519",
        "customerId": 2,
        "serviceModuleTypeId": 1,
        "name": "Slutt",
        "order": 10,
        "serviceGroupId": 0,
        "callLogVisible": true
    },
    {
        "soundFile": "ttt",
        "answer": true,
        "background": false,
        "nextModuleId": 410,
        "id": 14,
        "guid": "4bed4e33-0e41-4c37-969d-affa11b71751",
        "customerId": 2,
        "serviceModuleTypeId": 2,
        "name": "ÅPENT: Velkomstmelding",
        "order": 1,
        "serviceGroupId": 0,
        "callLogVisible": true
    },
    {
        "soundFile": "901",
        "answer": true,
        "background": false,
        "nextModuleId": 19,
        "id": 17,
        "guid": "521fbdd3-24c9-40be-9dbf-d824582a1adf",
        "customerId": 2,
        "serviceModuleTypeId": 2,
        "name": "STENGT: Ordinær stengtmelding",
        "order": 8,
        "serviceGroupId": 0,
        "callLogVisible": true
    },
    {
        "soundFile": "902",
        "answer": true,
        "background": false,
        "nextModuleId": 19,
        "id": 18,
        "guid": "4bf8e83d-eb35-47ce-87b5-b774f1e811e1",
        "customerId": 2,
        "serviceModuleTypeId": 2,
        "name": "STENGT: Helligdag stengtmelding",
        "order": 9,
        "serviceGroupId": 0,
        "callLogVisible": true
    },
    {
        "soundFile": "005",
        "answer": true,
        "background": true,
        "nextModuleId": 16,
        "id": 866,
        "guid": "6e0db7be-fde0-42d0-933e-3af08cc1d4e4",
        "customerId": 2,
        "serviceModuleTypeId": 2,
        "name": "Martine",
        "order": 12,
        "serviceGroupId": 0,
        "callLogVisible": false
    },
    {
        "soundFile": "006",
        "answer": true,
        "background": true,
        "nextModuleId": 16,
        "id": 867,
        "guid": "13e9f086-9453-4b71-871d-a1df07bc336b",
        "customerId": 2,
        "serviceModuleTypeId": 2,
        "name": "Amalie",
        "order": 13,
        "serviceGroupId": 0,
        "callLogVisible": false
    },
    {
        "macro": "set-eniro-callerid",
        "macroArgs": "",
        "nextModuleId": 408,
        "id": 370,
        "guid": "f7ca016a-c222-461d-bf79-8b63b60d5229",
        "customerId": 2,
        "serviceModuleTypeId": 13,
        "name": "eniro",
        "order": 4,
        "serviceGroupId": 0,
        "callLogVisible": false
    },
    {
        "variable": "z9601_vcode",
        "noMatchModuleId": 3472,
        "id": 543,
        "guid": "da4c0ecf-8501-4a28-b77c-79fafdff12f9",
        "customerId": 2,
        "serviceModuleTypeId": 24,
        "name": "multiswitch",
        "order": 11,
        "serviceGroupId": 0,
        "callLogVisible": true,
        "exits": [
            {
                "id": 1,
                "rule": "1",
                "nextModuleId": 867
            },
            {
                "id": 2,
                "rule": "2",    
                "nextModuleId": 866
            },
            {
                "id": 3,
                "rule": "3",
                "nextModuleId": 370
            }
        ]
    },
    {
        "queueId": 3,
        "queuePriority": 0,
        "queueTimeout": 0,
        "queueOptions": null,
        "answer": true,
        "extraTime": 0,
        "timeoutModuleId": 16,
        "joinEmptyModuleId": 16,
        "leaveEmptyModuleId": 16,
        "joinUnavailModuleId": 16,
        "leaveUnavailModuleId": 16,
        "fullModuleId": 16,
        "continueModuleId": 16,
        "surveyModuleId": 0,
        "id": 15,
        "guid": "dc14656e-e588-4bc6-ba36-67bada7c881a",
        "customerId": 2,
        "serviceModuleTypeId": 7,
        "name": "Sentralbord",
        "order": 6,
        "serviceGroupId": 0,
        "callLogVisible": true
    },
    {
        "queueId": 3287,
        "queuePriority": 0,
        "queueTimeout": 0,
        "queueOptions": null,
        "answer": true,
        "extraTime": 0,
        "timeoutModuleId": 16,
        "joinEmptyModuleId": 16,
        "leaveEmptyModuleId": 16,
        "joinUnavailModuleId": 16,
        "leaveUnavailModuleId": 16,
        "fullModuleId": 16,
        "continueModuleId": 16,
        "surveyModuleId": 0,
        "id": 8711,
        "guid": "c6c52bf3-ded5-4ac5-b64c-e18ec2c75304",
        "customerId": 2,
        "serviceModuleTypeId": 7,
        "name": "Test qeueu",
        "order": 16,
        "serviceGroupId": 0,
        "callLogVisible": false
    },
    {
        "soundFile": "000",
        "variable": "z9601_vcode",
        "maxDigits": 4,
        "timeout": 0,
        "acceptableDigits": "123A456B789C*0#D",
        "terminateDigits": "#",
        "terminateStartDigits": "",
        "keepTerminateDigit": false,
        "nextModuleId": 543,
        "timeoutModuleId": 543,
        "id": 407,
        "guid": "ef52c510-874b-4cd8-8b75-9790b31cc440",
        "customerId": 2,
        "serviceModuleTypeId": 23,
        "name": "z9601_vcode",
        "order": 3,
        "serviceGroupId": 0,
        "callLogVisible": false
    },
    {
        "nextModuleId": 15,
        "id": 408,
        "guid": "ca97f95d-b2d3-4af2-8bb1-532e423487c7",
        "customerId": 2,
        "serviceModuleTypeId": 34,
        "name": "SetVariable",
        "order": 5,
        "serviceGroupId": 0,
        "callLogVisible": false
    },
   
    {
        "wait": 2000,
        "nextModuleId": 407,
        "id": 410,
        "guid": "0c32560d-24d2-4ad5-9123-2dfe38577182",
        "customerId": 2,
        "serviceModuleTypeId": 17,
        "name": "wait2",
        "order": 2,
        "serviceGroupId": 0,
        "callLogVisible": false
    }
];
